name: Bug report
description: File a bug report
title: "[BUG]: <title>"
labels: ["bug"]
assignees: ["sandwichi"]
body:
- type: checkboxes
  id: existing_issue
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
- type: textarea
  id: current_behavior
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
- type: textarea
  id: reproduce_steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the software are you running?
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Kali 2024.1
    value: |
        - OS:
    render: markdown
- type: textarea
  id: extra
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
