name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: <title>"
assignees: ["sandwichi"]
body:
- type: checkboxes
  id: existing_issue
  attributes:
    label: Is there an existing feature request for this?
    description: Please search to see if a similar or identical feature request already exists.
    options:
    - label: I have searched the existing feature requests
- type: textarea
  id: problem
  attributes:
    label: Is your feature request related to a problem?
    description: Provide a clear and concise description of what the problem is.
    placeholder: I'm always frustrated when ...
- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like
    description: Provide a clear and concise description of what you want to happen.
- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered
    description: Provide a clear and concise description of any alternative solutions or features you've considered.
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the software are you running?
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Kali 2024.1
    value: |
        - OS:
    render: markdown
- type: textarea
  id: extra
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshots? Anything that will give us more context about your feature request!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
